# config/config.yaml

training:
  num_epochs: 4
  batch_size: 4
  num_workers: 1
  learning_rate: 0.0005
  weight_decay: 0.0002
  device: "cuda"
  output_model_path: "fasterrcnn.pth"

data:
  # Training data
  train_root_dir: "turbine_split/train"
  train_images_root: "../.."  
  train_annotation_file: "annotations.json"
  
  # Validation data
  val_root_dir: "turbine_split/val"
  val_images_root: "../.."  
  val_annotation_file: "annotations.json"
  
  # Test data
  test_root_dir: "turbine_split/test"
  test_images_root: "../.."  
  test_annotation_file: "annotations.json"

model:
  num_object_classes: 5